bookbarn/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('reviews.urls'), name='reviews_urls'),
    path("accounts/", include("allauth.urls")),
]

pages/urls.py
from django.urls import path
from .views import home_page_view

reviews/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path("", views.HomePageView.as_view(), name="home"),
    path("reviews/", views.ReviewList.as_view(), name="reviews"),
    path('myprofile/', views.ProfileViewList.as_view(), name='myprofile'),
    path('wishlist/', views.WishlistListView.as_view(), name='wishlist'),
    path('wishlist/remove/<int:pk>',
         views.WishListDeleteView.as_view(), name='remove_wishlist'),
    path('wishlist/add/<int:id>', views.add_to_wishlist, name='add_wishlist'),
    path('wishlist/toggle/<int:id>',
         views.wishlist_toggle_read, name='toggle_wishlist'),
    path('deleteprofile/<int:pk>',
         views.UserDeleteView.as_view(), name='deleteprofile'),
    path('search/', views.ReviewSearchResultsListView.as_view(),
         name='search_results'),
    path('review/<int:pk>/edit/',
         views.ReviewUpdateView.as_view(), name="review_edit"),
    path('comment/<int:pk>/delete',
         views.CommentDeleteView.as_view(), name='delete_comment'),
    path('comment/<int:pk>/edit',
         views.CommentUpdateView.as_view(), name='edit_comment'),
    path('<int:pk>/delete/',
         views.ReviewDeleteView.as_view(), name="review_delete"),
    path('add/', views.ReviewCreateView.as_view(), name='publish_review'),
    path('<int:id>/addcomment',
         views.CommentCreateView.as_view(), name='add_comment'),
    path('category/<category>', views.CategoryList.as_view(), name='category'),
    path('review/<int:pk>/',
         views.ReviewDetail.as_view(), name='review_detail'),

]

reviews/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from django.urls import reverse


""" Emoji strings used for star ratings"""
STAR_RATING = (
    (1, "⭐"),
    (2, "⭐⭐"),
    (3, "⭐⭐⭐"),
    (4, "⭐⭐⭐⭐"),
    (5, "⭐⭐⭐⭐⭐"),
)


class Category(models.Model):
    """Stores categories for book reviews"""
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Review(models.Model):
    """Main model holding book reviews"""
    title = models.CharField(max_length=250, unique=False,
                             verbose_name="Book Title")
    book_author = models.CharField(max_length=200, verbose_name="Book Author")
    """ Link to user """
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="reviews"
    )

    """ Cloudinary field to store book cover"""
    book_cover = CloudinaryField(
        'image',
        blank=True,
        transformation={
            'width': '625',
            'height': '1000',
            'crop': 'fill',
            'gravity': "auto"},
        default=("https://res.cloudinary.com/dpsodnurd/image/upload/v1652618629/zhtctppqjky78q8h760n.jpg"))
    """ Link to book category"""
    category = models.ForeignKey(
        Category, on_delete=models.PROTECT,
        default=1, verbose_name="Book Category")
    """ Main text of review """
    review_text = models.TextField()
    """ Date of publication"""
    published_on = models.DateTimeField(auto_now_add=True)
    """ Star rating out of 5"""
    star_rating = models.IntegerField(choices=STAR_RATING, default=5)
    """ Link to purchase book externally"""
    purchase_link = models.URLField(
        max_length=400, blank=True,
        verbose_name="Purchase Link URL"
    )

    class Meta:
        ordering = ["-published_on"]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """ Returns address of article"""
        return reverse('review_detail', args=[str(self.id)])


class Comment(models.Model):
    """ Blog comments model"""
    review = models.ForeignKey(Review, on_delete=models.CASCADE,
                               related_name="comments")
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="commentauthor"
    )
    """ Main text of comment"""
    comment_text = models.TextField()
    published_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["published_on"]

    def __str__(self):
        return self.comment_text


class WishlistItem(models.Model):
    """ Item for wishlist stores user and book review together"""
    review = models.ForeignKey(Review, on_delete=models.CASCADE,
                               related_name="wishlist")
    author = models.ForeignKey(
        User, on_delete=models.CASCADE,
        related_name="wishlistowner"
    )
    book_marked_as_read = models.BooleanField(default=False)
    published_on = models.DateTimeField(auto_now_add=True)

reviews/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.views import generic, View
from .models import Review, Comment, Category, WishlistItem
from django.urls import reverse_lazy
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required


class ReviewList(generic.ListView):
    """ Return a listview of all reviews, ordered by date and paginated """
    model = Review
    queryset = Review.objects.order_by("-published_on")
    paginate_by = 6
    template_name = "index.html"


class ReviewDetail(generic.DetailView):
    """Class based view passing to template, form is automatically generated"""
    model = Review
    template_name = "review_detail.html"


class ReviewCreateView(LoginRequiredMixin, generic.CreateView):
    """ Create a new reviews """
    model = Review
    """ Pass in al fields except post author"""
    fields = ['title', 'book_author', 'review_text', 'category',
              'book_cover', 'purchase_link', 'star_rating']
    template_name = "review_form.html"

    def form_valid(self, form):
        """ Set the author of the post to be the currently logged in user """
        form.instance.author = self.request.user
        return super().form_valid(form)


class ReviewUpdateView(LoginRequiredMixin,
                       UserPassesTestMixin, generic.UpdateView):
    """ Edit a published review """
    model = Review
    template_name = "review_edit.html"
    fields = ['title', 'book_author', 'review_text', 'category', 'book_cover',
              'purchase_link', 'star_rating']

    def test_func(self):
        """ Check that the user editing the post is creator of the post """
        obj = self.get_object()
        return obj.author == self.request.user


class ReviewDeleteView(LoginRequiredMixin,
                       UserPassesTestMixin, generic.DeleteView):
    """ Delete a review from the site"""
    model = Review
    template_name = 'review_delete.html'
    success_url = reverse_lazy('reviews')

    """ Check for ownership of review"""

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user


class ReviewSearchResultsListView(generic.ListView):
    """ Use GET to pass in search, paginate results and pass to template"""
    model = Review
    context_object_name = 'review_list'
    template_name = 'search_results.html'
    paginate_by = 6

    def get_queryset(self):
        query = self.request.GET.get('searchterm')
        return Review.objects.filter(
            Q(title__icontains=query) | Q(review_text__icontains=query)
        )


class ProfileViewList(LoginRequiredMixin, generic.ListView):
    """ Creates view of the profile page, with reviews written by the user"""
    model = Review
    queryset = Review.objects.order_by("-published_on")
    template_name = "profile_view.html"

    def get_queryset(self):
        return Review.objects.filter(
            author=self.request.user).order_by('-published_on')


class UserDeleteView(LoginRequiredMixin,
                     UserPassesTestMixin, generic.DeleteView):
    """ Allows user to delete their own account"""
    model = User
    template_name = 'user_delete.html'
    """ Redirect to home page after"""
    success_url = reverse_lazy('home')
    success_message = "Your account has been deleted"

    def test_func(self):
        """ Check for correct permissions to delete account"""
        obj = self.get_object()
        return obj.id == self.request.user.id


class CommentCreateView(LoginRequiredMixin, generic.CreateView):
    """ Create a new comment which is attached to a review page"""
    model = Comment
    fields = ['comment_text', ]
    template_name = "add_comment.html"
    """ Redirect to parent comment after successfully posting"""

    def get_success_url(self):
        return reverse_lazy('review_detail', args=(self.object.review.id,))

    def form_valid(self, form):
        """ The author of the comment is the currently logged in user"""
        form.instance.author = self.request.user
        """ The current review is found and attached to the comment"""
        queryset = Review.objects.all()
        current_review = get_object_or_404(queryset, id=self.kwargs['id'])
        form.instance.review = current_review
        return super().form_valid(form)


class CommentDeleteView(LoginRequiredMixin,
                        UserPassesTestMixin, generic.DeleteView):
    """ Allow user to delete their own comment"""
    model = Comment
    template_name = "comment_delete.html"
    fields = ['comment_text', ]

    def get_success_url(self):
        return reverse_lazy('review_detail', args=(self.object.review.id,))

    def test_func(self):
        """ Check for ownership first"""
        obj = self.get_object()
        """The comment can be deleted by author or by author of the review"""
        return (obj.author == self.request.user) or (
            obj.review.author == self.request.user
        )


class CommentUpdateView(LoginRequiredMixin,
                        UserPassesTestMixin, generic.UpdateView):
    """ Update a user comment"""
    model = Comment
    template_name = "comment_edit.html"
    fields = ['comment_text', ]

    def get_success_url(self):
        return reverse_lazy('review_detail', args=(self.object.review.id,))

    def test_func(self):
        """ Check for permissions first"""
        obj = self.get_object()
        return obj.author == self.request.user


class CategoryList(generic.ListView):
    """Takes GET request, returns articles by category"""
    model = Category
    template_name = "category.html"
    context_object_name = 'categorylist'

    def get_queryset(self):
        content = {
            'cat': self.kwargs['category'],
            'reviews': Review.objects
            .filter(category__name=self.kwargs['category'])
        }
        return content


def review_category_list(request):
    """ Creates a list of categories to be used by navbar for dropdown menu"""
    review_category_list = Category.objects.all()
    context = {"review_category_list": review_category_list, }
    return context


@login_required
def add_to_wishlist(request, id):
    """ Adds a book review to the user's wishlist"""
    """ Checks the review exists to avoid accessing nonexistent objects"""
    try:
        bookreview = Review.objects.get(id=id)
    except BaseException:
        """If not, return to the wishlist page """
        return HttpResponseRedirect(reverse_lazy('wishlist'))
    """Make sure the wishlist object does not exists already """
    if WishlistItem.objects.filter(author=request.user,
                                   review=bookreview).count() > 0:
        return HttpResponseRedirect(reverse_lazy('wishlist'))
    """ Create the wishlist item and return the user to wishlist page"""
    WishlistItem.objects.create(author=request.user, review=bookreview)
    return HttpResponseRedirect(reverse_lazy('wishlist'))


@login_required
def wishlist_toggle_read(request, id):
    """ Toggles the boolean value to show if a book is read/unread"""
    try:
        wishlist = WishlistItem.objects.get(id=id)
    except BaseException:
        return HttpResponseRedirect(reverse_lazy('wishlist'))
    wishlist.book_marked_as_read = not wishlist.book_marked_as_read
    wishlist.save()
    """ Returns to page that made request"""
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


class WishlistListView(LoginRequiredMixin, generic.ListView):
    """ Creates view of wishlist page for user"""
    model = WishlistItem
    context_object_name = 'wishlist'
    template_name = 'wishlist_view.html'
    """ Return all objects belonging to user in reverse chronological order"""

    def get_queryset(self):
        return WishlistItem.objects.filter(
            author=self.request.user
        ).order_by('-published_on')


class WishListDeleteView(LoginRequiredMixin,
                         UserPassesTestMixin, generic.DeleteView):
    """ Allows deletion of wishlist items after checking for ownership"""
    model = WishlistItem
    template_name = 'wishlist_delete.html'
    success_url = reverse_lazy('wishlist')

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user


class HomePageView(generic.TemplateView):
    """ Static home page template"""
    template_name = 'home.html'

templates/add_comment.html
{% extends 'base.html' %} {% block content %}
{% load static %} {% load crispy_forms_tags %}{% load cloudinary %}


<!-- add new comment to review page -->
  <div class="container">
    <div class="row">
      <div class="col-sm-10 col-md-10 col-lg-7 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body">
            <h3 class="text-center"><b>Add your comment</b></h3>
            <br />
              <form class="" method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <!-- return to main reviews page -->
                <div class="d-grid">
                  <a class="btn btn-warning btn-lg mt-2 mb-2" href="{% url 'reviews' %}">Cancel</a>
                </div>

                  <div class="d-grid">
                    <button class="btn btn-primary btn-lg mt-3 mb-2" id="submitButton" type="submit">Submit Comment</button>
                  </div>
                </div>
              
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/base.html
{% load static %}
{% load active_link_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- favicon -->
  <link rel="shortcut icon"
    href="https://res.cloudinary.com/dpsodnurd/image/upload/v1652399538/Martz90-Circle-Books_zkovp3.ico" />
  <!-- bootstrap css -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <!-- font aswesome icons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
  <!-- bootsrap icons -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
  <!-- static css file -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block form_css %}
  {% endblock  %}
  <title>Book Barn</title>
</head>
<!-- main body set to min height for footer -->
<body class="d-flex flex-column min-vh-100">
  <!-- navbar -->
  <nav class="navbar navbar-dark navbar-expand-lg" style="background-color: #022a46;">
    <!-- restrict navbar size -->
    <div class="container-lg">
      <!-- home link and logo -->
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="https://res.cloudinary.com/dpsodnurd/image/upload/v1652468731/book-4986_zdlsii.svg" alt=""
          height="24" class="d-inline-block align-text-middle mx-1">
        Book Barn
      </a>
      <!-- collapsible elements for mobile menu -->
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'reviews' %}">Book Reviews</a>
          </li>
          <!-- check for user logged in -->
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'publish_review' %}"> Add Review</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myprofile' %}">Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'wishlist' %}">Wishlist</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_login' %}">Login</a>
          </li>
          {% endif %}
        </ul>
        <ul class="navbar-nav me-3 mb-2 mb-lg-0">
          <!-- drop down categories list -->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
              aria-expanded="false">
              Categories
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <!-- get list of categories from database -->
              {% for category in review_category_list %}
              <li><a class="dropdown-item" href="/category/{{ category.name}}">
                {{ category.name }}
              </a>
            </li>
              {% endfor %}
            </ul>
          </li>
        </ul>
        <!-- search box -->
        <form class="d-flex" action="{% url 'search_results' %}" method="get">
          <input class="form-control me-2" type="search" name="searchterm" placeholder="Search" aria-label="Search">
        </form>
      </div>
    </div>
  </nav>
  <!-- display user messages -->
  <div class="container">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
          {{ message | safe }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>

  {% block content %}
  <!-- Content Goes here -->
  {% endblock content %}

  <footer class="footer mt-auto text-center">
    <div class="container">
      <!-- Footer Social Icons-->
      <div class="col-lg-12 mb-5 mb-lg-0">
        <h4 class="text-uppercase mb-3">Social Links</h4>
        <a class="btn btn-outline-light btn-social mx-1" href="http://www.facebook.com" target="_blank"
          aria-label="Open our Facebook page in a new window"><i class="fab fa-fw fa-facebook-f"></i></a>
        <a class="btn btn-outline-light btn-social mx-1" href="http://www.instagram.com" target="_blank"
          aria-label="Open our instagram page in a new window"><i class="fab fa-fw fa-instagram"></i></a>
        <a class="btn btn-outline-light btn-social mx-1" href="http://www.twitter.com" target="_blank"
          aria-label="Open our twitter page in a new window"><i class="fab fa-fw fa-twitter"></i></a>
        <a class="btn btn-outline-light btn-social mx-1" href="http://www.linkedin.com" target="_blank"
          aria-label="Open our linkedIn page in a new window"><i class="fab fa-fw fa-linkedin-in"></i></a>
        <a class="btn btn-outline-light btn-social mx-1" href="http://www.github.com" target="_blank"
          aria-label="Open our Github page in a new window"><i class="fab fa-fw fa-github"></i></a>
      </div>
    </div>
  </footer>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
  </script>
</body>

</html>

templates/category.html
{% extends 'base.html' %} 
{% load static %}
{% load cloudinary %}
{% block title%} categorylist {%endblock title%}
{% block content %}

<div class="container-sm py-4 bg-light">
  <h3 class="display-5 fw-bold text-center">{{categorylist.cat}} Reviews</h3>
</div>

<div class="container-sm py-4 bg-light">
  <div class="row row-cols-1 row-cols-md-3 g-4">
    {% for review in categorylist.reviews %}
    <div class="col">
      <div class="card text-center">
        <!-- show book cover and link to review page -->
        <a href="{{ review.get_absolute_url }}"><img src="{{review.book_cover.url}}" class="card-img-top" alt="book cover image"></a>
        <div class="card-body">
          <!-- display book reveiw details -->
          <h5 class="card-title">{{ review.title }}</h5>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">By {{review.book_author}}</li>
            <li class="list-group-item">Reviewed by {{review.author}}</li>
            <li class="list-group-item">Rating: {{review.get_star_rating_display}}</li>
            <li class="list-group-item d-grid"><a href="{{ review.get_absolute_url }}" class="btn btn-primary">Read
                Review</a></li>
          </ul>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>


{% endblock content %}

templates/comment_delete.html
{% extends 'base.html' %} {% block content %}





<!-- form to confirm deletion of comment -->
  <div class="container">
    <div class="row">
      <div class="col-sm-10 col-md-10 col-lg-7 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body">
            <br />
              <form class="" method="POST" action="">
                {% csrf_token %}
                    <h2 class="text-center">Are you sure you want to delete this comment?</h2>
                    <div class="form-group">
                      <div class="d-grid">
                        <button class="btn btn-danger btn-lg mt-3 mb-2" id="submitButton" type="submit">Delete</button>
                      </div>
                    </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/comment_edit.html
{% extends 'base.html' %} {% block content %}
{% load static %} {% load crispy_forms_tags %}{% load cloudinary %}

      <!-- for to edit comments left on reveiws -->

  <div class="container">
    <div class="row">
      <div class="col-sm-10 col-md-10 col-lg-7 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body">
            <h3 class="text-center"><b>Edit your comment</b></h3>
            <br />
            <form class="" method="POST">
              {% csrf_token %}
              {{ form|crispy }}
              <div class="d-grid">
                <a class="btn btn-warning btn-lg mt-2 mb-2" href="{{ view.get_success_url }}">Cancel</a>
              </div>
              <div class="d-grid">
                <button class="btn btn-primary btn-lg mt-3 mb-2" id="submitButton" type="submit">Update Comment</button>
              </div>
          </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  </div>
{% endblock content %}

templates/home.html
{% extends "base.html" %}
{% load static %}
{% load cloudinary %}
{% block content %}
<!-- static home page template -->
<div class="container col-xxl-8 px-4 py-5 my-5 bg-light">
  <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
    <div class="col-10 col-sm-8 col-lg-6">
      <!-- hero image -->
      <img src="https://res.cloudinary.com/dpsodnurd/image/upload/c_scale,w_742/v1652492708/jamie-street-Zqy-x7K5Qcg-unsplash_up1xut.jpg" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes" width="700" height="500" loading="lazy">
    </div>
    <div class="col-lg-6">
      <h1 class="display-5 fw-bold lh-1 mb-3">Welcome to the Book Barn review site!</h1>
      <p class="lead">Here you'll find interesting reviews of all types of books written by readers just like you. Register for an account to start writing your own reviews, use our commenting system and make a wishlist of books to read. Or just start reading!</p>
      <div class="d-grid">
        <a class="btn btn-success btn-lg mt-2 mb-2" href="{% url 'account_signup' %}">Register!</a>
      </div>
      <div class="d-grid">
        <a class="btn btn-primary btn-lg mt-2 mb-2" href="{% url 'reviews' %}">Start Reading Reviews</a>
      </div>
    </div>
  </div>
</div>

{%endblock%}

templates/index.html
{% extends "base.html" %}
{% load static %}
{% load cloudinary %}
{% block content %}


<!-- main review page loops thorugh all available reviews and paginates -->
<div class="container-sm p-4 bg-light">
  <div class="row row-cols-1 row-cols-md-3 g-4">
    {% for review in review_list %}
    <div class="col">
      <div class="card text-center">
        <a href="{{ review.get_absolute_url }}"><img src="{{review.book_cover.url}}" class="card-img-top" alt="book cover image"></a>
        <div class="card-body">
          <h5 class="card-title">{{ review.title }}</h5>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">By {{review.book_author}}</li>
            <li class="list-group-item">Reviewed by {{review.author}}</li>
            <li class="list-group-item">Rating: {{review.get_star_rating_display}}</li>
            <li class="list-group-item d-grid"><a href="{{ review.get_absolute_url }}" class="btn btn-primary">Read
                Review</a></li>
          </ul>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>

  <br>
  <!-- pagination -->
  <div class="pagination justify-content-center">
    <span class="step-links">
      {% if page_obj.has_previous %}
      <a href="?page=1">&laquo; first</a>
      <a href="?page={{ page_obj.previous_page_number }}">previous</a>
      {% endif %}
      <span class="current">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
      </span>
      {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">next</a>
      <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
      {% endif %}
    </span>
    <br><br>
  </div>
</div>



{%endblock%}

templates/review_detail.html
{% extends 'base.html' %}
{% load static %}
{% load cloudinary %}
{% block content %}

<!-- show detail view of each review -->
<div class="container-lg bg-light mt-3">
    <div class="row">
        <div class="col h-100">
            <div class="px-4 py-2 my-5 text-center">
                <!-- title -->
                <h3 class="display-5 fw-bold">{{review.title}}</h3>
                <div class="col-lg-6 mx-auto">
                    <p class="lead mb-4">by {{review.book_author}}, reviewed by {{review.author}}</p>
                </div>
            </div>
            <div class="container-sm my-4">
                <div class="row">
                    <!-- show book cover -->
                    <div class="col-md-6">
                        <img src="{{ review.book_cover.url }}" class="img-fluid rounded-start" alt="book review cover">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <!-- show review details -->
                            <p class="card-text">Review: {{ review.review_text }}</p>
                            <p class="card-text display-6">Star Rating: {{review.get_star_rating_display}}</p>
                            {% if user == review.author %}
                            <div class="d-grid">
                                <a class="btn btn-warning btn-lg mt-2 mb-2"
                                    href="{% url 'review_edit' review.id %}">Edit Review</a>
                            </div>
                            <div class="d-grid">
                                <a class="btn btn-danger btn-lg mt-2 mb-2"
                                    href="{% url 'review_delete' review.id %}">Delete Review</a>
                            </div>
                            {%endif%}
                            <!-- check for purchase link -->
                            {% if review.purchase_link %}
                            <div class="d-grid">
                                <a class="btn btn-success btn-lg mt-2 mb-2" href="{{review.purchase_link}}"
                                    target="_blank">Purchase Book</a>
                            </div>
                            {%endif%}
                            <!-- add to wishlist button -->
                            <div class="d-grid">
                                <a class="btn btn-success btn-lg mt-2 mb-2"
                                    href="{% url 'add_wishlist' review.id %}">Add to Wishlist</a>
                            </div>
                            <!-- comments section -->
                            <h4 class="my-2">Comments</h4>
                            <a href="{%url 'add_comment' review.id %}">Add comment</a><br>
                            <br>
                            {%if not review.comments.all %}
                            No comments . . .
                            {%else%}
                            {% for comment in review.comments.all %}
                            <div class="card" style="width: 18rem;">
                                <div class="card-body">
                                    <h5 class="card-title">{{ comment.author}}</h5>
                                    <h6 class="card-subtitle mb-2 text-muted">{{comment.published_on}}
                                    </h6>
                                    <p class="card-text"> {{ comment.comment_text }}</p>
                                    {% if user == comment.author %}
                                    <a href="{%url 'delete_comment' comment.id%}" class="card-link">Delete</a>
                                    <a href="{%url 'edit_comment' comment.id%}" class="card-link">Edit</a>
                                    {%endif%}
                                    {% if user == review.author %}
                                    <a href="{%url 'delete_comment' comment.id%}" class="card-link">Remove</a>
                                    {%endif%}
                                </div>
                            </div>
                            {%endfor%}
                            {%endif%}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}